"""Initial migration

Revision ID: 298ac05a2c6f
Revises: 
Create Date: 2026-01-22 20:31:18.181961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '298ac05a2c6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_verifications_email'), table_name='email_verifications')
    op.drop_table('email_verifications')
    op.alter_column('categories', 'color_hex',
               existing_type=sa.CHAR(length=7),
               type_=sa.String(length=7),
               existing_nullable=False,
               existing_server_default=sa.text("'#3B82F6'::bpchar"))
    op.alter_column('categories', 'icon',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Tag'::character varying"))
    op.drop_index(op.f('idx_categories_workspace'), table_name='categories')
    op.drop_index(op.f('idx_installment_groups_workspace'), table_name='installment_groups')
    op.drop_index(op.f('idx_transactions_category'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_workspace_date'), table_name='transactions')
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_workspace_id'), 'transactions', ['workspace_id'], unique=False)
    op.alter_column('users', 'email',
               existing_type=postgresql.CITEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'])
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_transactions_workspace_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.create_index(op.f('idx_transactions_workspace_date'), 'transactions', ['workspace_id', sa.literal_column('transaction_date DESC')], unique=False)
    op.create_index(op.f('idx_transactions_category'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('idx_installment_groups_workspace'), 'installment_groups', ['workspace_id'], unique=False)
    op.create_index(op.f('idx_categories_workspace'), 'categories', ['workspace_id'], unique=False)
    op.alter_column('categories', 'icon',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Tag'::character varying"))
    op.alter_column('categories', 'color_hex',
               existing_type=sa.String(length=7),
               type_=sa.CHAR(length=7),
               existing_nullable=False,
               existing_server_default=sa.text("'#3B82F6'::bpchar"))
    op.create_table('email_verifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('email_verifications_pkey')),
    sa.UniqueConstraint('token', name=op.f('email_verifications_token_key'))
    )
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=False)
    # ### end Alembic commands ###

